"""________________________________Tuple___________________________________"""

#()

"""Tuple is the immutable (No modification) data type in the python.
you can not change, update or modify the values in the typle.
it is the ordered data type. 
Tuple is the container that store all types of elements
i.g.. str, int, bool,float.(it is the hetrogeneous data type.)
it is allowed Duplicates.
"""

T1= (1,2,3,4)
print(type(T1))
# T2 =(1)  #this is int
T2 =(1,)  #, इज  complsory, when you want to represent the tuple'
print(type(T2))